import { BiLogoPostgresql } from "react-icons/bi";
import { FaJava } from "react-icons/fa";
import {
  SiCodeigniter,
  SiCss3,
  SiDjango,
  SiAstro,
  SiExpress,
  SiFirebase,
  SiBootstrap,
  SiFlask,
  SiFramer,
  SiGithub,
  SiGulp,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiLaravel,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPrisma,
  SiPython,
  SiReact,
  SiReactquery,
  SiRedux,
  SiSass,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiStreamlit,
  SiSpring,
  SiMongodb,
  SiFastapi,
  SiAmazonwebservices,
  SiVercel,
  SiNetlify,
} from "react-icons/si";
import { ISkill } from "@/common/types/skill";

const iconSize = "100%";

export const STACKS: ISkill = {
  Java: <FaJava size={iconSize} className="transition-icon hover:text-primary" />,
  Spring: <SiSpring size={iconSize} className="transition-icon hover:text-[#77bc1f]" />,
  PHP: <SiPhp size={iconSize} className="transition-icon hover:text-[#707fc0]" />,
  Laravel: <SiLaravel size={iconSize} className="transition-icon hover:text-red-600" />,
  CodeIgniter: <SiCodeigniter size={iconSize} className="transition-icon hover:text-red-600" />,
  Flask: <SiFlask size={iconSize} className="transition-icon hover:text-primary" />,
  Django: <SiDjango size={iconSize} className="transition-icon hover:text-green-800" />,
  Fastapi: <SiFastapi size={iconSize} className="transition-icon hover:text-[#05998b]" />,
  JavaScript: <SiJavascript size={iconSize} className="transition-icon hover:text-yellow-400" />,
  TypeScript: <SiTypescript size={iconSize} className="transition-icon hover:text-blue-400" />,
  "Next.js": <SiNextdotjs size={iconSize} className="transition-icon hover:text-primary" />,
  "React.js": <SiReact size={iconSize} className="transition-icon hover:text-sky-500" />,
  "Astro.js": <SiAstro size={iconSize} className="transition-icon hover:text-primary" />,
  TailwindCSS: <SiTailwindcss size={iconSize} className="transition-icon hover:text-cyan-300" />,
  Bootstrap: <SiBootstrap size={iconSize} className="transition-icon hover:text-purple-500" />,
  Vite: <SiVite size={iconSize} className="transition-icon hover:text-purple-500" />,
  PostgreSql: <BiLogoPostgresql size={iconSize} className="transition-icon hover:text-blue-500" />,
  MongoDB: <SiMongodb size={iconSize} className="transition-icon hover:text-[#589636]" />,
  SASS: <SiSass size={iconSize} className="transition-icon hover:text-pink-600" />,
  Gulp: <SiGulp size={iconSize} className="transition-icon hover:text-red-500" />,
  Firebase: <SiFirebase size={iconSize} className="transition-icon hover:text-yellow-500" />,
  "Framer Motion": <SiFramer size={iconSize} className="transition-icon hover:text-primary" />,
  Jest: <SiJest size={iconSize} className="transition-icon hover:text-orange-600" />,
  "Express.js": <SiExpress size={iconSize} className="transition-icon hover:text-primary" />,
  Redux: <SiRedux size={iconSize} className="transition-icon hover:text-purple-500" />,
  "React Query": <SiReactquery size={iconSize} className="transition-icon hover:text-red-600" />,
  HTML: <SiHtml5 size={iconSize} className="transition-icon hover:text-orange-500" />,
  CSS: <SiCss3 size={iconSize} className="transition-icon hover:text-blue-500" />,
  Prisma: <SiPrisma size={iconSize} className="transition-icon hover:text-primary" />,
  "Node JS": <SiNodedotjs size={iconSize} className="transition-icon hover:text-green-600" />,
  Github: <SiGithub size={iconSize} className="transition-icon hover:text-primary" />,
  Python: <SiPython size={iconSize} className="transition-icon hover:text-yellow-400" />,
  Streamlit: <SiStreamlit size={iconSize} className="transition-icon hover:text-red-500" />,
  AWS: <SiAmazonwebservices size={iconSize} className="transition-icon hover:text-primary" />,
  Vercel: <SiVercel size={iconSize} className="transition-icon hover:text-primary" />,
  Netlify: <SiNetlify size={iconSize} className="transition-icon hover:text-[#06bdb8]" />,
};